apiVersion : apps/v1 
kind: Deployment 
metadata: 
  name: react-app-cicd-deployment
  labels: 
    app: react-app-cicd
  namespace: react-app-cicd
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: react-app-cicd
  template: 
    metadata: 
      labels: 
        app: react-app-cicd
    spec:
      containers: 
      - name: react-app-container
        image: mthang1801/react-app-cicd:latest
        ports:
          - containerPort: 80
            name: http-web-svc
    
---

apiVersion: v1 
kind: Service
metadata: 
  name: react-app-cicd-svc
  namespace: react-app-cicd
spec:
  selector : 
    app: react-app-cicd
  type: NodePort
  ports:
  - name: react-app-cicd-service
    protocol: TCP 
    port: 80
    targetPort: http-web-svc
    nodePort: 30000
